baseURL = "https://ridingintraffic.github.io/wiki/"
title = "wiki"
theme = "after-dark"
publishDir = "docs"

# config file (default is path/config.yaml|json|toml)
config =                     "config.toml"

canonifyURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  subtitle = "Hugo is Absurdly Fast!"
  author = "John Doe"